-- Enable Row Level Security (good practice, though we will interact via service role/connection string mainly)
-- Create Clinics Table
CREATE TABLE IF NOT EXISTS public.clinics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hp_id TEXT UNIQUE NOT NULL,
    name TEXT,
    name_kana TEXT,
    prefecture TEXT,
    area TEXT,
    url TEXT,
    scraped_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Clinic Details Table
CREATE TABLE IF NOT EXISTS public.clinic_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT REFERENCES public.clinics(id) ON DELETE CASCADE,
    postal_code TEXT,
    address TEXT,
    access TEXT,
    access_guide TEXT,
    phone_number TEXT,
    opening_hours TEXT,
    close_days TEXT,
    credit_cards TEXT,
    medical_loan TEXT,
    catch_copy TEXT,
    description TEXT,
    staff_count TEXT,
    counseling_rooms TEXT,
    beds TEXT,
    private_rooms TEXT,
    powder_rooms TEXT,
    main_image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Menus Table
CREATE TABLE IF NOT EXISTS public.menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT REFERENCES public.clinics(id) ON DELETE CASCADE,
    category TEXT,
    menu_name TEXT,
    price TEXT,
    price_note TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Doctors Table
CREATE TABLE IF NOT EXISTS public.doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT REFERENCES public.clinics(id) ON DELETE CASCADE,
    name TEXT,
    name_kana TEXT,
    job_title TEXT,
    profile TEXT,
    message TEXT,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Cases Table
CREATE TABLE IF NOT EXISTS public.cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT REFERENCES public.clinics(id) ON DELETE CASCADE,
    title TEXT,
    category TEXT,
    price TEXT,
    method TEXT,
    concern TEXT,
    risk TEXT,
    before_image_url TEXT,
    after_image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Reviews Table
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT REFERENCES public.clinics(id) ON DELETE CASCADE,
    total_rating NUMERIC,
    rating_atmosphere NUMERIC,
    rating_booking NUMERIC,
    rating_service NUMERIC,
    rating_tech NUMERIC,
    latest_review_date TEXT,
    review_count INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Indexes for performance
CREATE INDEX IF NOT EXISTS idx_clinics_hp_id ON public.clinics(hp_id);
CREATE INDEX IF NOT EXISTS idx_clinics_scraped_at ON public.clinics(scraped_at);
